nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "${PORT}:${PORT}" # Exposes Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount custom Nginx configuration
    networks:
      - frontend
      - backend # Connect to both networks to route traffic
    depends_on:
      - web
      - api
    restart: unless-stopped

    networks:

  frontend:
    driver: bridge
    
  backend:
    driver: bridge